export function create(): vec4;
export function clone(a: ReadonlyVec4): vec4;
export function fromValues(x: number, y: number, z: number, w: number): vec4;
export function copy(out: vec4, a: ReadonlyVec4): vec4;
export function set(out: vec4, x: number, y: number, z: number, w: number): vec4;
export function add(out: vec4, a: ReadonlyVec4, b: ReadonlyVec4): vec4;
export function subtract(out: vec4, a: ReadonlyVec4, b: ReadonlyVec4): vec4;
export function multiply(out: vec4, a: ReadonlyVec4, b: ReadonlyVec4): vec4;
export function divide(out: vec4, a: ReadonlyVec4, b: ReadonlyVec4): vec4;
export function ceil(out: vec4, a: ReadonlyVec4): vec4;
export function floor(out: vec4, a: ReadonlyVec4): vec4;
export function min(out: vec4, a: ReadonlyVec4, b: ReadonlyVec4): vec4;
export function max(out: vec4, a: ReadonlyVec4, b: ReadonlyVec4): vec4;
export function round(out: vec4, a: ReadonlyVec4): vec4;
export function scale(out: vec4, a: ReadonlyVec4, b: number): vec4;
export function scaleAndAdd(out: vec4, a: ReadonlyVec4, b: ReadonlyVec4, scale: number): vec4;
export function distance(a: ReadonlyVec4, b: ReadonlyVec4): number;
export function squaredDistance(a: ReadonlyVec4, b: ReadonlyVec4): number;
export function length(a: ReadonlyVec4): number;
export function squaredLength(a: ReadonlyVec4): number;
export function negate(out: vec4, a: ReadonlyVec4): vec4;
export function inverse(out: vec4, a: ReadonlyVec4): vec4;
export function normalize(out: vec4, a: ReadonlyVec4): vec4;
export function dot(a: ReadonlyVec4, b: ReadonlyVec4): number;
export function cross(out: vec4, u: ReadonlyVec4, v: ReadonlyVec4, w: ReadonlyVec4): vec4;
export function lerp(out: vec4, a: ReadonlyVec4, b: ReadonlyVec4, t: number): vec4;
export function random(out: vec4, scale?: number | undefined): vec4;
export function transformMat4(out: vec4, a: ReadonlyVec4, m: ReadonlyMat4): vec4;
export function transformQuat(out: vec4, a: ReadonlyVec4, q: ReadonlyQuat): vec4;
export function zero(out: vec4): vec4;
export function str(a: ReadonlyVec4): string;
export function exactEquals(a: ReadonlyVec4, b: ReadonlyVec4): boolean;
export function equals(a: ReadonlyVec4, b: ReadonlyVec4): boolean;
export function sub(out: vec4, a: ReadonlyVec4, b: ReadonlyVec4): vec4;
export function mul(out: vec4, a: ReadonlyVec4, b: ReadonlyVec4): vec4;
export function div(out: vec4, a: ReadonlyVec4, b: ReadonlyVec4): vec4;
export function dist(a: ReadonlyVec4, b: ReadonlyVec4): number;
export function sqrDist(a: ReadonlyVec4, b: ReadonlyVec4): number;
export function len(a: ReadonlyVec4): number;
export function sqrLen(a: ReadonlyVec4): number;
export function forEach(a: any, stride: any, offset: any, count: any, fn: any, arg: any): any;
