import { RenderBuffer } from "../../ascii3d.js";
import { Camera } from "../utilities.js";
import * as rgbaShader from "../shaders/rgba.js";
import * as waterShader from "../shaders/water.js";
import { vertices as cubeModel } from "../models/cube.js";
import { vertices as waterModel } from "../models/water.js";
export declare const canvas: HTMLCanvasElement;
export declare const ctx: CanvasRenderingContext2D;
export declare const renderBuffer: RenderBuffer;
export declare const reflectionTexture: RenderBuffer;
export declare const playerCamera: Camera;
export declare const reflectionCamera: Camera;
export declare const cubeModelMatrix: Float32Array;
export { rgbaShader as rgbShader, waterShader };
export { cubeModel, waterModel };
export declare const variables: {
    renderWater: boolean;
};
export declare function configure(width: number, height: number, resolution: number, fontSize: number): void;
export declare function renderFrame(frame: number, renderWater: boolean): void;
